
services:
  api: 
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - APP_ORIGIN=${APP_ORIGIN}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    ports:
      - 4000:4000
    command: npm run dev