const enum ErrorCode {
    AUTH_EMAIL_ALREADY_EXISTS = "AUTH_EMAIL_ALREADY_EXISTS",
    AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN",
    AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND",
    AUTH_TOO_MANY_ATTEMPTS = "AUTH_TOO_MANY_ATTEMPTS",
    AUTH_UNAUTHORIZED_ACCESS = "AUTH_UNAUTHORIZED_ACCESS",
    AUTH_TOKEN_NOT_FOUND = "AUTH_TOKEN_NOT_FOUND",

    // ACCESS CONTROL ERRORS
    ACCESS_FORBIDDEN = "ACCESS_FORBIDDEN",
    ACCESS_UNAUTHORIZED = "ACCESS_UNAUTHORIZED",

    // vALIDATION AND RESOURCE ERRORS
    VALIDATION_ERROR = "VALIDATION_ERROR",
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",

    // SYSTEM ERRORS
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    VERIFICATION_ERROR = "VERIFICATION_ERROR",

    ROLE_ALREADY_EXIST = "ROLE_ALREADY_EXIST",
    ROLE_NOT_FOUND = "ROLE_NOT_FOUND",
    PERMISSION_ALREADY_EXIST= "PERMISSION_ALREADY_EXIST",
    PERMISSION_NOT_FOUND = "PERMISSION_NOT_FOUND",
    FORBIDDEN= "FORBIDDEN",
    PERMISSION_IN_USE = "PERMISSION_IN_USE",
    INCORRECT_EMAIL= "INCORRECT_EMAIL",
    ABUSE="ABUSE"
    

}

export {ErrorCode};