name: Build and Deploy to Render

on:
  push:
    branches:
      - master
env:
    DOCKER_PASSWORD: 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
    DOCKER_USERNAME: MotteyAmos
    RENDER_DEPLOY_HOOK_URL: https://api.render.com/deploy/srv-d1d7osumcj7s73fhvubg?key=njcEltd7icg
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_USERNAME }}/throttle-app-image:latest .

      - name: Push Docker image
        run: docker push ${{ env.DOCKER_USERNAME }}/throttle-app-image:latest

      - name: Trigger Deploy on Render
        run: |
          curl -X POST ${{ env.RENDER_DEPLOY_HOOK_URL }}
