name: Build and Deploy to Render

on:
  push:
    branches:
      - master
env:
    DOCKER_PASSWORD: 
    DOCKER_USERNAME: MotteyAmos
    RENDER_DEPLOY_HOOK_URL: https://api.render.com/deploy/srv-d1d7osumcj7s73fhvubg?key=njcEltd7icg
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ env.DOCKER_PASSWORD }}" | docker login ghcr.io --username ${{env.DOCKER_USERNAME}}  --password ${{env.DOCKER_PASSWORD}}

      - name: Build Docker image
        run: docker build -t ghcr.io/motteyamos/throttle-app-image .

      - name: Push Docker image
        run: docker push ghcr.io/motteyamos/throttle-app-image

      - name: Trigger Deploy on Render
        run: |
          curl -X POST ${{ env.RENDER_DEPLOY_HOOK_URL }}
