name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Compile TypeScript
        run: npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: motteyamos
          password: dckr_pat_wYImMQi9nkvk1oNx-atY466VOTU
          
            
      - name: Build and push Docker image to Docker Hub
        id: docker-build
        env:
          IMAGE_NAME: motteyamos/throttle-test
          IMAGE_TAG: latest
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG
          echo "image=$IMAGE_NAME:$IMAGE_TAG" >> $GITHUB_OUTPUT

      # Optional ECS deployment (if still using ECS)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: AKIAR7X6S6T7U35DRAJV
          aws-secret-access-key: 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
          aws-region: eu-west-1

      - name: Render ECS task definition with Docker Hub image
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: thr-con-test.json
          container-name: thro-test
          image: ${{ steps.docker-build.outputs.image }}

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: thro-app-service
          cluster: thro-test
          wait-for-service-stability: true
